### ISSUE TITLE
我又来了。能否某个脚本可以不用代理。

### ISSUE THREAD

**Issue by kent9111** [XgzK/IP_cistern#13]
我这里有个 多库自动去重复脚本，只要挂了代理，就报错，不挂代理就行。

**Comment by XgzK** [comment]
> 我这里有个 多库自动去重复脚本，只要挂了代理，就报错，不挂代理就行。

不清楚怎么让特定脚本不走代理，这个可以找qinglong开发者反馈，不过可以把报错的脚本错误发下，应该可以找到问题

**Comment by kent9111** [comment]
日志-禁用重复任务
## 开始执行... 2022-06-13 20:23:28

当前代理: socks5://119.23.71.164:8880
开始查询公网IP:
当前IP: 119.23.71.164
归属地: 中国 广东 深圳
# 当前总共 58 个 JD_COOKIE。

如果报错请在环境变量中添加你的真实 IP:端口
名称：IPPORT	值：127.0.0.1:5700
或在 config.sh 中添加 export IPPORT='127.0.0.1:5700'
===> 禁用重复任务开始 <===
加载推送功能中...

=== 你选择过滤的任务前缀为 ===
KingRan_KR
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/lib/python3.9/site-packages/socks.py", line 443, in _negotiate_SOCKS5
    self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
  File "/usr/lib/python3.9/site-packages/socks.py", line 533, in _SOCKS5_request
    raise SOCKS5Error("{:#04x}: {}".format(status, error))
socks.SOCKS5Error: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/contrib/socks.py", line 96, in _new_conn
    conn = socks.create_connection(
  File "/usr/lib/python3.9/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/usr/lib/python3.9/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/contrib/socks.py", line 127, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSConnection object at 0x7f6e0d047fa0>: Failed to establish a new connection: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPConnectionPool(host='localhost', port=5700): Max retries exceeded with url: /api/crons?searchValue=&t=1655123023451 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f6e0d047fa0>: Failed to establish a new connection: 0x05: Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/scripts/KingRan_KR/jd_disable.py", line 188, in <module>
    tasklist = get_tasklist()
  File "/ql/scripts/KingRan_KR/jd_disable.py", line 58, in get_tasklist
    response = requests.get(url=url, headers=headers)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPConnectionPool(host='localhost', port=5700): Max retries exceeded with url: /api/crons?searchValue=&t=1655123023451 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f6e0d047fa0>: Failed to establish a new connection: 0x05: Connection refused'))

## 执行结束... 2022-06-13 20:23:43 耗时 16 秒

**Comment by kent9111** [comment]
日志-禁用重复任务
## 开始执行... 2022-06-13 20:23:28

当前代理: socks5://119.23.71.164:8880
开始查询公网IP:
当前IP: 119.23.71.164
归属地: 中国 广东 深圳
# 

如果报错请在环境变量中添加你的真实 IP:端口
名称：IPPORT	值：127.0.0.1:5700
或在 config.sh 中添加 export IPPORT='127.0.0.1:5700'
===> 禁用重复任务开始 <===
加载推送功能中...

=== 你选择过滤的任务前缀为 ===
KingRan_KR
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/lib/python3.9/site-packages/socks.py", line 443, in _negotiate_SOCKS5
    self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
  File "/usr/lib/python3.9/site-packages/socks.py", line 533, in _SOCKS5_request
    raise SOCKS5Error("{:#04x}: {}".format(status, error))
socks.SOCKS5Error: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/contrib/socks.py", line 96, in _new_conn
    conn = socks.create_connection(
  File "/usr/lib/python3.9/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/usr/lib/python3.9/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/contrib/socks.py", line 127, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSConnection object at 0x7f6e0d047fa0>: Failed to establish a new connection: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPConnectionPool(host='localhost', port=5700): Max retries exceeded with url: /api/crons?searchValue=&t=1655123023451 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f6e0d047fa0>: Failed to establish a new connection: 0x05: Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/scripts/KingRan_KR/jd_disable.py", line 188, in <module>
    tasklist = get_tasklist()
  File "/ql/scripts/KingRan_KR/jd_disable.py", line 58, in get_tasklist
    response = requests.get(url=url, headers=headers)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPConnectionPool(host='localhost', port=5700): Max retries exceeded with url: /api/crons?searchValue=&t=1655123023451 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f6e0d047fa0>: Failed to establish a new connection: 0x05: Connection refused'))

## 执行结束... 2022-06-13 20:23:43 耗时 16 秒

**Comment by XgzK** [comment]
> 禁用重复任务

刚刚测试了下好像用不用代理都会报错

**Comment by kent9111** [comment]
不用代理正常。

**Comment by XgzK** [comment]
> 不用代理正常。

刚刚关掉代理，的时候依然不正常，不过可以添加在这个脚本使用的那一分钟自动删除代理，一分钟后再添加上的定时任务

**Comment by kent9111** [comment]
怎么操作呢

**Comment by XgzK** [comment]
第一种配合Linux的定时任务设置清空代理，直接参考往文件里面添加代理
第二行添加python代码，设置个定时任务

kent9111 ***@***.***> 于 2022年6月14日周二 08:02写道：

**Comment by XgzK** [comment]
> 我这里有个 多库自动去重复脚本，只要挂了代理，就报错，不挂代理就行。

已经更新某个时间段取消代理，请阅读文档设置
