### ISSUE TITLE
您好 今天我手动运行时就报错 代码如下 

### ISSUE THREAD

**Issue by atpx4869** [XgzK/IP_cistern#2]
# python3 ip_broker.py 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2e59af2d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='uu-proxy.com', port=443): Max retries exceeded with url: /api/free (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e59af2d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ip_broker.py", line 125, in <module>
    while_loop()
  File "ip_broker.py", line 71, in while_loop
    data = get_ip()
  File "ip_broker.py", line 25, in get_ip
    strhtml = requests.get(url).text
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='uu-proxy.com', port=443): Max retries exceeded with url: /api/free (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e59af2d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by XgzK** [comment]
> 
国内服务器吗

**Comment by atpx4869** [comment]
嗯 家宽 ipv4

**Comment by XgzK** [comment]
> u-proxy.com

用下这个 ‘curl https://uu-proxy.com/api/free’ 看看返回什么

**Comment by XgzK** [comment]
> 嗯 家宽 ipv4

用下这个 ‘curl [https://uu-proxy.com/api/free’](https://uu-proxy.com/api/free%E2%80%99) 看看返回什么

**Comment by atpx4869** [comment]
## curl https://uu-proxy.com/api/free
curl: (6) Could not resolve: uu-proxy.com (Timeout while contacting DNS servers)

**Comment by atpx4869** [comment]
> > 嗯 家宽 ipv4
> 
> 用下这个'curl [https://uu-proxy.com/api/free'](https://uu-proxy.com/api/free%E2%80%99)看看返回什么

dns超时 emmm 跟我的openwrt有关系吗

**Comment by atpx4869** [comment]
可以了 应该是我的dns服务器有问题 换成了smartdns就好了 
 谢啦 大佬
